""
" vimrc by fs
"
set nocompatible
set encoding=utf-8
set modelines=0
set visualbell
set noshowmode
set showcmd
set relativenumber
set cursorline
set colorcolumn=80
set hidden
set splitbelow
set splitright
set title
set showmatch
set list
" set listchars+=eol:$
set nobackup
set noswapfile
set undofile
set wildmenu
set wildmode=longest,full

syntax on
filetype plugin indent on

"" Whitespace
set autoindent
set copyindent
set nowrap
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set smarttab
set expandtab                  " use soft tabs (spaces)
set backspace=indent,eol,start " backspace through everythong in insert mode
set textwidth=79

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault

if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

set omnifunc=syntaxcomplete#Complete " completion stuff

" enable powerline for airline
let g:airline_powerline_fonts = 1

" Enhance Netrw usability
let g:netrw_browse_split = 4
let g:netrw_altv = 1

let g:snipMate = {}
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['scss'] = 'scss,css'

let g:rspec_command = 'call Send_to_Tmux("rspec {spec}\n")'

if has('autocmd')
  " NERDTree
  autocmd vimenter * if !argc() | NERDTree | endif
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
endif

" Keymaps

let mapleader = ','

" default / to perl-style regexp's
nnoremap / /\v
vnoremap / /\v

" remove highligted terms
nnoremap <Leader><Space> :noh<CR>

" use tab to jump between matching brackets
nnoremap <Tab> %

" delete trailing whitespace
nnoremap <Leader>W :%s/\s\+$//<CR>:let @/=''<CR>

" re-hardwrap text
nnoremap <Leader>q gqip

" reselect last pasted text
nnoremap <Leader>v V`]

" go from insert to normal mode
inoremap jj <Esc>

" disable arrows
noremap  <Up>    <Nop>
noremap  <Down>  <Nop>
noremap  <Left>  <Nop>
noremap  <Right> <Nop>

" easier navigation between split windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Switch between the last two files
nnoremap <Leader>c <C-^>

map <Leader>n :NERDTreeToggle<CR>
map <Leader>, :tabedit $MYVIMRC<CR>
map <Leader>< :tabedit $MYGVIMRC<CR>

nnoremap <Leader>u :GundoToggle<CR>

nnoremap <Leader>t :call RunCurrentSpecFile()<CR>
nnoremap <Leader>s :call RunNearestSpec()<CR>
nnoremap <Leader>l :call RunLastSpec()<CR>

call togglebg#map('<F5>')
