alias bat='docker run -it --rm -e BAT_THEME -e BAT_STYLE -e BAT_TABS -v "$(pwd):/myapp" danlynn/bat'
alias bx="bundle exec"
alias cdgr="cd \`git root\`"
alias git="hub"
alias mk="make"
alias n="nvim"
alias ndark="nvim +'colorscheme solarized8_dark'"
alias nlight="nvim +'colorscheme solarized8_light'"
alias pacs="sudo pacman -S"
alias rk="rake"
alias vhalt="vagrant halt"
alias vssh="vagrant ssh"
alias vup="vagrant up"
alias vi="vim"
alias vplug="vim +PlugInstall +qall"
alias nvplug="nvim +PlugInstall +qall"
alias yt="youtube-dl -t"
alias y="yay -S"
alias zdd="$EDITOR ${ZDOTDIR:-$HOME}"

alias cp="${aliases[cp]:-cp} -v"
alias ln="${aliases[ln]:-ln} -v"
alias mv="${aliases[mv]:-mv} -v"
alias rm="${aliases[rm]:-rm} -v"

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias j="fasd_jump"
alias nv="fasd_edit"

alias nude="nu utils docker-env"
alias nusss="nu security scope show"
alias nussa="nu security scope add"
alias nussf="nu security scope find"
alias numq="nu mordor query --accept application/json"
alias nuclone="nu projects clone"
alias zagallo="nu inutils zagallo"
