[arch]
packages = [
  "1password",
  "1password-cli",
  "autoconf",
  "automake",
  "base",
  "base-devel",
  "bcwc-pcie-git",
  "binutils",
  "bison",
  "blueman",
  "bluez-utils",
  "brightnessctl",
  "broadcom-wl-dkms",
  "clang",
  "consolas-font",
  "dconf-editor",
  "dialog",
  { name = "docker", hooks = { after_sync = [
    "sh",
    "-c",
    "sudo systemctl enable docker && sudo usermod --append --groups docker $USER",
  ] } },
  "docker-compose",
  "dosfstools",
  "dunst",
  "efibootmgr",
  "elephant",
  "elephant-desktopapplications",
  "evtest",
  "fakeroot",
  "file",
  "findutils",
  "firefox",
  "fish",
  "flex",
  "gammastep",
  "gawk",
  "gcc",
  { name = "gdm", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "gdm",
  ] } },
  "gettext",
  "git",
  "git-delta",
  "grep",
  "grim",
  "groff",
  "gthumb",
  "gucharmap",
  "gzip",
  "htop",
  "hyfetch",
  "inetutils",
  "jq",
  "jump",
  "kanshi",
  "keyd",
  "kitty",
  "lib32-gcc-libs",
  "lib32-glibc",
  "libtool",
  "libxcrypt-compat",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "linux-lts-headers",
  "lvm2",
  "m4",
  "make",
  "man-db",
  "man-pages",
  "mbpfan-git",
  "metapac",
  "mise",
  "moreutils",
  "mtools",
  "namcap",
  "nautilus",
  "ncdu",
  "neovim",
  "networkmanager",
  "networkmanager-dmenu-git",
  "nmap",
  "nodejs",
  "nordvpn-bin",
  "noto-fonts",
  "noto-fonts-emoji",
  "nwg-displays",
  "nwg-look",
  "openssh",
  "os-prober",
  "pacman",
  "pamixer",
  "parallel",
  "paru",
  "pass",
  "patch",
  "pavucontrol",
  "pkgconf",
  "powerline-fonts-git",
  "python-pip",
  "ranger",
  "ripgrep",
  "rlwrap",
  "rofi",
  "rofi-dmenu",
  "rofimoji",
  "rofi-power-menu",
  "screen",
  "seahorse",
  "sed",
  "slurp",
  "stow",
  "sudo",
  "sway",
  "swaybg",
  "swayidle",
  "swaylock",
  "terminus-font",
  "texinfo",
  "tmux",
  "tree",
  "ttf-dejavu",
  "ttf-scientifica",
  "usbutils",
  "vim",
  "vlc",
  "vlc-plugins-all",
  "walker-bin",
  "watchexec",
  "waybar",
  "which",
  "whois",
  "cliphist",
  "wireless-regdb", # without this, kernel falls back to world regulatory domain (wrong channels/power for region)
  "wl-clipboard",
  "wtype",
  "xdg-desktop-portal-wlr",
  "xf86-input-mtrack-git",
  "xorg-xwayland",
  "zsh",
  "rsync",
]
