AllCops:
  TargetRubyVersion: 2.6

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/BlockDelimiters:
  EnforcedStyle: semantic

Metrics/LineLength:
  Max: 100

