import = [
  "~/.local/share/alacritty/themes/alacritty-theme/themes/rose-pine.toml"
]

[cursor.style]
blinking = "Always"
shape = "Block"

[cursor]
blink_timeout = 0

[font]
size = 16

[font.bold]
family = "ProFont IIx Nerd Font"
style = "Regular"

[font.italic]
family = "ProFont IIx Nerd Font"
style = "Regular"

[font.normal]
family = "ProFont IIx Nerd Font"
style = "Regular"
